[package]
name = "problem_management"
version = "0.1.0"
edition = "2021"

[lib]
name="problem_management"
path="src/lib.rs"
proc-macro=true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.77"
